packages:
  - "apps/*"
  - "packages/*"
  - "scripts/*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@brennoluan/alfabit-button@0.1.1"
  - "@brennoluan/alfabit-tokens@0.1.0"
  - '@brennoluan/alfabit-button@1.0.0'
